version: '3'

volumes:
  wordpress:
    driver_opts:
      device: /home/aboudoun/data/wp_files
      o: bind
      type: none
  mariadb:
    driver_opts:
      device: /home/aboudoun/data/wp_database
      o: bind
      type: none

networks:
  inception:
    name: inception
    driver: bridge

services:
  mariadb:
    env_file: .env
    build: ./requirements/mariadb
    image: mariadb:13
    container_name: mariadb
    networks:
      - inception
    ports:
      - 3306
    volumes:
      - mariadb:/var/lib/mysql
    restart: on-failure

  wordpress:
    env_file: .env
    build: ./requirements/wordpress
    image: wordpress:13
    container_name: wordpress
    networks:
      - inception
    ports:
      - 9000
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mariadb
    restart: on-failure


  nginx:
    env_file: .env
    build: ./requirements/nginx
    image: nginx:13
    container_name: nginx
    networks:
      - inception
    ports:
      - 443
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - wordpress
    restart: on-failure



