version: '3.7'

networks:
  inception:
    name: inception
    driver: bridge

volumes:
  wordpress:
    name: wp_files
    driver_opts:
      device: /home/aboudoun/data/wp_files
      o: bind
      type: none
  mariadb:
    name: wp_database
    driver_opts:
      device: /home/aboudoun/data/wp_database
      o: bind
      type: none

services:
  mariadb:
    env_file: .env
    build: ./requirements/mariadb
    image: mariadb:1337
    container_name: mariadb
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql
    restart: always

  wordpress:
    env_file: .env
    build: ./requirements/wordpress
    image: wordpress:1337
    container_name: wordpress
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mariadb
    restart: always


  nginx:
    env_file: .env
    build: ./requirements/nginx
    image: nginx:1337
    container_name: nginx
    networks:
      - inception
    ports:
      - 443:443
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - wordpress
    restart: always
