CREATE DATABASE IF NOT EXISTS wpdb;
CREATE USER IF NOT EXISTS 'root'@'%' IDENTIFIED BY '123456789';
CREATE USER IF NOT EXISTS 'wpuser'@'%' IDENTIFIED BY 'wp123456789';
GRANT ALL ON wpdb.* TO '$WORDPRESS_DB_USER'@'%';
GRANT ALL ON *.* TO 'root'@'%';
FLUSH PRIVILEGES;
