CREATE DATABASE IF NOT EXISTS wpdb;
CREATE USER 'root'@'%' IDENTIFIED BY '123456789';
CREATE USER 'wpuser'@'%' IDENTIFIED BY 'wp123456789';
GRANT ALL ON wpdb.* TO 'wpuser'@'%';
GRANT ALL ON *.* TO 'root'@'%';
FLUSH PRIVILEGES;
